FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

# Either serve static files with a lightweight server for development
# CMD ["npx", "serve", "-s", "build"]

# Or just keep container alive since Nginx will serve the files
CMD ["tail", "-f", "/dev/null"]