version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend